# Generated by Django 5.1.1 on 2024-09-04 13:31

import workshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, db_index=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='Скидка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=workshop.models.product_preview_directory_path, verbose_name='Основное фото')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
    ]
