# Generated by Django 5.1.1 on 2024-09-04 16:08

import django.db.models.deletion
import workshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('description', models.TextField(blank=True, verbose_name='Пожелания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workshop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заметки к фото'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=workshop.models.product_images_directory_path, verbose_name='Фото'),
        ),
    ]
